## Project 2 Dataset 1

In [9]:
#import numpy and pandas, and DataFrame / Series
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import datetime

In [16]:
#Read data from file 'MissingMigrantsDatasetCSV.csv' 
data = pd.read_csv("C:/Users/KATERINE/Documents/cuny classes/DATA ACQ AND MANAGEM/week 6/MissingMigrantsDatasetCSV.csv", encoding='latin-1')
df = pd.DataFrame(data, columns= ['id', 'cause_of_death', 'region_origin', 'affected_nationality', 'missing', 'dead', 'incident_region', 'date', 'source', 'reliability', 'lat', 'Ion'])
print (df)

     id                                     cause_of_death  \
0     1                                  Presumed drowning
1     3                                    Fell from train
2     4                                  Presumed drowning
3     6                                           Drowning
4     7                                   Vehicle accident
5     8                                           Drowning
6     9                                           Drowning
7    10                                           Drowning
8    11                                           Drowning
9    12  Died of unknown cause in hospital shortly afte...
10   13                                           Drowning
11   14                                  Presumed drowning
12   15                                  Presumed drowning
13   16                                           Drowning
14   17         Exposure. Died upon entry to refugee camp.
15   18                                           Drowning
16   19                                           Drowning
17   20                                           Drowning
18   21                                           Drowning
19   22                                           Drowning
20   23                                           Drowning
21   24                                                NaN
22   25                                           Drowning
23   28                                           Drowning
24   29                                           Drowning
25   30                                           Drowning
26   31                                           Drowning
27   32                                  Presumed drowning
28   33                                  Presumed drowning
29   34                                           Drowning
..  ...                                                ...
69   86                                           Drowning
70   87                                   Crushed to death
71   89                                           Drowning
72   91                                  Presumed drowning
73   92                                       Hit by train
74   94                                  Presumed drowning
75   95                                  Presumed drowning
76   97                                           Drowning
77   98                                           Drowning
78  100                 Drowning. Boat collided with ferry
79  101                                    Fell from train
80  102                                           Drowning
81  103                                           Drowning
82  104                                      Electrocution
83  105                                                NaN
84  106                                           Drowning
85  107                                           Drowning
86  108                                           Drowning
87  109                                     Hit by vehicle
88  111                                  Presumed drowning
89  112                                                NaN
90  113                          Unknown, torture involved
91  114                                     Train accident
92  119                                           Drowning
93  120                                           Drowning
94  121                             Drowning, Asphyxiation
95  122  Burns from cooking gas explosion in connection...
96  123                                           Drowning
97  124  Drowning after being thrown overboard by other...
98  125                                           Drowning

               region_origin  \
0                Middle East
1   Central America & Mexico
2                Middle East
3                       MENA
4            South East Asia
5                       MENA
6                       MENA
7                       MENA
8                        NaN
9                       MENA
10                      MENA
11                South Asia
12   Middle East/ South Asia
13                       NaN
14                South Asia
15                       NaN
16        Sub-Saharan Africa
17   Middle East/ South Asia
18                       NaN
19   Middle East/ South Asia
20   Middle East/ South Asia
21                       NaN
22                       NaN
23   Middle East/ South Asia
24   Middle East/ South Asia
25   Middle East/ South Asia
26                       NaN
27   Middle East/ South Asia
28   Middle East/ South Asia
29                       NaN
..                       ...
69                      MENA
70   Middle East/ South Asia
71                      MENA
72   Middle East/ South Asia
73            Horn of Africa
74   Middle East/ South Asia
75   Middle East/ South Asia
76               Middle East
77   Middle East/ South Asia
78   Middle East/ South Asia
79  Central America & Mexico
80               Middle East
81                      MENA
82   Middle East/ South Asia
83        Sub-Saharan Africa
84               Middle East
85                      MENA
86                      MENA
87            Horn of Africa
88                       NaN
89           South East Asia
90           South East Asia
91                      MENA
92  Central America & Mexico
93                       NaN
94                       NaN
95        Sub-Saharan Africa
96        Sub-Saharan Africa
97        Sub-Saharan Africa
98                       NaN

                                 affected_nationality  missing   dead  \
0                                                Iraq      1.0    1.0
1                                            Honduras      NaN    1.0
2                                                 NaN      NaN    1.0
3                                                 NaN      6.0    4.0
4                                            Cambodia      NaN    4.0
5                                                 NaN      NaN   11.0
6                                                 NaN      NaN    1.0
7                                                 NaN      NaN    1.0
8                                                 NaN      0.0    3.0
9                                               Syria      NaN    1.0
10                                               Iran      NaN    1.0
11                                        Afghanistan      7.0    3.0
12                                                NaN      NaN    1.0
13                                        Afghanistan      NaN    4.0
14                                             Afghan      NaN    1.0
15                                                NaN      NaN    1.0
16                                    Likely Comorian      NaN    8.0
17                                                NaN      NaN    1.0
18                                                NaN     32.0    7.0
19                                                NaN      4.0    3.0
20                                                NaN      2.0    NaN
21                                                NaN      NaN    8.0
22                                                NaN      NaN    1.0
23                                                NaN      NaN    4.0
24                                                NaN      NaN    2.0
25                                                NaN      1.0    3.0
26                                        Afghanistan      NaN    3.0
27                                                NaN      NaN   19.0
28                                                NaN      NaN    1.0
29                                        Afghanistan      NaN    1.0
..                                                ...      ...    ...
69                                              Syria      5.0    1.0
70                                              Iraqi      NaN    1.0
71         Mostly from Syria, possibly some from Iraq      NaN   17.0
72                                                NaN      NaN    1.0
73                                     Likely Eritrea      NaN    1.0
74                                                NaN      NaN    1.0
75                                                NaN      NaN    1.0
76                                       Syrian Kurds     24.0    2.0
77                                                NaN      2.0    NaN
78                                                NaN     13.0   13.0
79                                                NaN      NaN    1.0
80                                              Syria      NaN   13.0
81                                             Syrian      NaN    1.0
82                                              Syria      NaN    1.0
83                                           Nigerian      NaN    1.0
84  Reported as unspecified nationals of Syria, Af...      NaN   22.0
85                                             Syrian      NaN    2.0
86                                              Syria      NaN    1.0
87                                            Eritrea      NaN    1.0
88                                                NaN      NaN   10.0
89                                           Rohingya      NaN   36.0
90                                            Myanmar      NaN  106.0
91                                        Afghanistan      NaN    1.0
92                                                NaN      NaN    1.0
93                             Eritrea (2), Syria (1)      NaN    3.0
94  Syria, Somalia, Gambia, Ivory Coast, Mali, Tun...      NaN  750.0
95                                 Eritrea or Somalia      NaN    1.0
96               Survivors from Nigeria, Ghana, Niger      NaN   41.0
97                                     Ghana, Nigeria     12.0    NaN
98                                                NaN    391.0    9.0

                 incident_region        date  \
0                  Mediterranean   5/11/2015
1   Central America incl. Mexico   3/11/2015
2                  Mediterranean   3/11/2015
3                  Mediterranean   1/11/2015
4                 Southeast Asia   1/11/2015
5                  Mediterranean   1/11/2015
6                  Mediterranean   1/11/2015
7                  Mediterranean   1/11/2015
8                  Mediterranean  28/10/2015
9                  Mediterranean  28/10/2015
10                 Mediterranean  26/10/2015
11                 Mediterranean  23/10/2015
12                 Mediterranean   1/11/2015
13                 Mediterranean  31/10/2015
14                        Europe  31/10/2015
15                 Mediterranean  30/10/2015
16            Sub-Saharan Africa  30/10/2015
17                 Mediterranean  30/10/2015
18                 Mediterranean  29/10/2015
19                 Mediterranean  29/10/2015
20                 Mediterranean  29/10/2015
21                 Mediterranean  20/10/2015
22                 Mediterranean   2/10/2015
23                 Mediterranean  29/10/2015
24                 Mediterranean  28/10/2015
25                 Mediterranean  28/10/2015
26                 Mediterranean  28/10/2015
27                 Mediterranean  28/10/2015
28                 Mediterranean   1/10/2015
29                 Mediterranean  28/10/2015
..                           ...         ...
69                 Mediterranean  29/09/2015
70                        Europe  29/09/2015
71                 Mediterranean  27/09/2015
72                 Mediterranean  24/09/2015
73                        Europe  24/09/2015
74                 Mediterranean  23/09/2015
75                 Mediterranean  22/09/2015
76                 Mediterranean  20/09/2015
77                 Mediterranean  20/09/2015
78                 Mediterranean  20/09/2015
79  Central America incl. Mexico  20/09/2015
80                 Mediterranean  19/09/2015
81                 Mediterranean  18/09/2015
82                        Europe  18/09/2015
83                 Mediterranean  17/09/2015
84                 Mediterranean  15/09/2015
85                 Mediterranean  14/09/2015
86                 Mediterranean    5/9/2015
87                        Europe  24/07/2015
88                 Mediterranean    2/5/2015
89                Southeast Asia    1/5/2015
90                Southeast Asia  25/05/2015
91                        Europe  24/04/2015
92            U.S./Mexico Border  21/04/2015
93                 Mediterranean  20/04/2015
94                 Mediterranean  18/04/2015
95                 Mediterranean  17/04/2015
96                 Mediterranean  16/04/2015
97                 Mediterranean  16/04/2015
98                 Mediterranean  13/04/2015

                                       source         reliability        lat  \
0                                  IOM Greece            Verified  36.891500
1                                  La Jornada  Partially Verified  15.956400
2                        Hellenic Coast Guard            Verified  36.504390
3                                     Reuters  Partially Verified  37.285600
4                             Phnom Penh Post  Partially Verified  13.361100
5                        Hellenic Coast Guard            Verified  37.751814
6                        Hellenic Coast Guard            Verified  38.357540
7                        Hellenic Coast Guard            Verified  39.276195
8                                          AP  Partially Verified  37.457800
9                                  IOM Greece            Verified  39.370816
10                                 IOM Greece            Verified  39.280978
11                                 IOM Greece            Verified  39.273005
12                       Hellenic Coast Guard            Verified  39.274069
13                        Hurriyet Daily News  Partially Verified  39.279915
14                                         AP  Partially Verified  45.260400
15                                         AP  Partially Verified  39.274069
16                                      LINFO  Partially Verified -11.802800
17                       Hellenic Coast Guard            Verified  37.457800
18                             Reuters España            Verified  35.244600
19                                         AP  Partially Verified  36.435000
20                                         AP  Partially Verified  37.754800
21                                   IOM Rome            Verified  40.334718
22                                 IOM Greece            Verified  36.952300
23                        Hurriyet Daily News  Partially Verified  39.470142
24                                         AP            Verified  39.269816
25  Associated Press and Hellenic Coast Guard            Verified  37.754800
26                     Reuters and Al Jazeera  Partially Verified  39.274600
27                                         AP  Partially Verified  36.952300
28                       Hellenic Coast Guard            Verified  36.952300
29                       Hellenic Coast Guard            Verified  39.277258
..                                        ...                 ...        ...
69                        Hurriyet Daily News  Partially verified  40.676541
70                                        BBC  Partially Verified  50.951300
71                        Hurriyet Daily News  Partially Verified  37.013567
72        Hellenic Coast Guard via IOM Greece            Verified  37.466700
73                                        BBC  Partially Verified  50.923200
74                                 IOM Greece            Verified  39.367100
75                             IOM Greece/AFP  Partially Verified  39.382400
76                                 IOM Greece            Verified  39.419600
77                        Coast Guard Command            Verified  39.235700
78     IOM/Coast Guard Command/Indian Express  Partially Verified  39.445562
79                                 Red-accion  Partially Verified  19.709800
80                                 IOM Greece            Verified  39.387700
81                             Anadolu Agency  Partially Verified  38.328609
82                                        BBC  Partially Verified  50.951500
83        Migrant Offshore Aid Station (MOAS)            Verified  33.724300
84           RTE News and Turkish Coast Guard            Verified  36.719100
85                        Hurriyet Daily News  Partially Verified  38.007019
86                                 IOM Greece            Verified  37.500500
87                                The Express  Partially Verified  50.148700
88                                    BBC/CBC  Partially Verified  35.460700
89                             Arakan Project            Verified   7.189770
90                                        BBC  Partially Verified   6.444910
91                          Radio Free Europe  Partially Verified  41.557900
92                                   Televisa  Partially Verified  27.495413
93                                    Reuters  Partially Verified  36.352782
94                                  IOM Italy            Verified  35.030000
95                                      UNHCR            Verified  35.173800
96                                BBC and CBC  Partially Verified  35.746500
97                                BBC and CBC  Partially Verified  34.885900
98                                   Guardian  Partially Verified  36.173400

           Ion
0    27.287700
1   -93.663100
2    27.363253
3    27.086600
4   100.985000
5    26.960291
6    26.452157
7    26.383443
8    26.972100
9    26.176473
10   26.384130
11   26.423269
12   26.386190
13   26.388937
14   19.170600
15   26.388250
16   43.851900
17   26.972100
18   -3.931750
19   28.217500
20   26.977800
21   17.164603
22   26.980800
23   26.592653
24   26.390310
25   26.977800
26   26.392370
27   26.980800
28   26.980800
29   26.409536
..         ...
69   25.948853
70    1.858690
71   27.181960
72   26.966700
73    1.782850
74   26.175100
75   26.486400
76   26.450700
77   26.665000
78   26.042874
79  -98.971500
80   26.431500
81   26.293587
82    1.845700
83   14.436000
84   27.338800
85   27.101857
86   27.079100
87    1.889650
88   14.414100
89  100.595000
90  100.578535
91   21.818800
92  -99.522649
93   27.938259
94   14.677700
95   17.226600
96   14.414100
97   14.414100
98   17.572607

[99 rows x 12 columns]

In [15]:
#Reading the last five rows
data.tail()

,id,cause_of_death,region_origin,affected_nationality,missing,dead,incident_region,date,source,reliability,lat,Ion
94,121,"Drowning, Asphyxiation",NaN,"Syria, Somalia, Gambia, Ivory Coast, Mali, Tun...",NaN,750.0,Mediterranean,18/04/2015,IOM Italy,Verified,35.0300,14.677700
95,122,Burns from cooking gas explosion in connection...,Sub-Saharan Africa,Eritrea or Somalia,NaN,1.0,Mediterranean,17/04/2015,UNHCR,Verified,35.1738,17.226600
96,123,Drowning,Sub-Saharan Africa,"Survivors from Nigeria, Ghana, Niger",NaN,41.0,Mediterranean,16/04/2015,BBC and CBC,Partially Verified,35.7465,14.414100
97,124,Drowning after being thrown overboard by other...,Sub-Saharan Africa,"Ghana, Nigeria",12.0,NaN,Mediterranean,16/04/2015,BBC and CBC,Partially Verified,34.8859,14.414100
98,125,Drowning,NaN,NaN,391.0,9.0,Mediterranean,13/04/2015,Guardian,Partially Verified,36.1734,17.572607

In [18]:
#Handling missing values with NULL.   When something is not NULL, it will show a false.  Additionally, it will show true if something is missing
data.isnull().tail()

,id,cause_of_death,region_origin,affected_nationality,missing,dead,incident_region,date,source,reliability,lat,Ion
94,False,False,True,False,True,False,False,False,False,False,False,False
95,False,False,False,False,True,False,False,False,False,False,False,False
96,False,False,False,False,True,False,False,False,False,False,False,False
97,False,False,False,False,False,True,False,False,False,False,False,False
98,False,False,True,True,False,False,False,False,False,False,False,False

In [20]:
#Number of missing values per column
data.isnull().sum()

id                       0
cause_of_death           7
region_origin           24
affected_nationality    46
missing                 75
dead                     3
incident_region          0
date                     0
source                   0
reliability              0
lat                      0
Ion                      0
dtype: int64

In [30]:
#Examinning subsets of data frame from the cause_of_death column to look for missing values only
data[data.cause_of_death.isnull()]

,id,cause_of_death,region_origin,affected_nationality,missing,dead,incident_region,date,source,reliability,lat,Ion
21,24,NaN,NaN,NaN,NaN,8.0,Mediterranean,20/10/2015,IOM Rome,Verified,40.334718,17.164603
35,42,NaN,NaN,Nigerian,NaN,1.0,Mediterranean,23/08/2015,IOM Tunisia,Verified,34.865700,12.604900
43,53,NaN,South East Asia,NaN,NaN,24.0,Southeast Asia,23/08/2015,"BBC, UNHCR",Verified,6.444910,100.205000
45,57,NaN,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,18/10/2015,Hellenic Coast Guard via IOM Greece,Verified,37.295400,27.112700
67,83,NaN,South America,Ecuadorian,NaN,3.0,Central America incl. Mexico,30/09/2015,El Universo,Partially Verified,19.173800,-96.134200
83,105,NaN,Sub-Saharan Africa,Nigerian,NaN,1.0,Mediterranean,17/09/2015,Migrant Offshore Aid Station (MOAS),Verified,33.724300,14.436000
89,112,NaN,South East Asia,Rohingya,NaN,36.0,Southeast Asia,1/5/2015,Arakan Project,Verified,7.189770,100.595000

In [31]:
#Examinning subsets of data frame from the region_origin column to look for missing values only
data[data.region_origin.isnull()]

,id,cause_of_death,region_origin,affected_nationality,missing,dead,incident_region,date,source,reliability,lat,Ion
8,11,Drowning,NaN,NaN,0.0,3.0,Mediterranean,28/10/2015,AP,Partially Verified,37.457800,26.972100
13,16,Drowning,NaN,Afghanistan,NaN,4.0,Mediterranean,31/10/2015,Hurriyet Daily News,Partially Verified,39.279915,26.388937
15,18,Drowning,NaN,NaN,NaN,1.0,Mediterranean,30/10/2015,AP,Partially Verified,39.274069,26.388250
18,21,Drowning,NaN,NaN,32.0,7.0,Mediterranean,29/10/2015,Reuters España,Verified,35.244600,-3.931750
21,24,NaN,NaN,NaN,NaN,8.0,Mediterranean,20/10/2015,IOM Rome,Verified,40.334718,17.164603
22,25,Drowning,NaN,NaN,NaN,1.0,Mediterranean,2/10/2015,IOM Greece,Verified,36.952300,26.980800
26,31,Drowning,NaN,Afghanistan,NaN,3.0,Mediterranean,28/10/2015,Reuters and Al Jazeera,Partially Verified,39.274600,26.392370
29,34,Drowning,NaN,Afghanistan,NaN,1.0,Mediterranean,28/10/2015,Hellenic Coast Guard,Verified,39.277258,26.409536
31,36,Drowning,NaN,NaN,13.0,43.0,Mediterranean,28/10/2015,IOM Greece and Hellenic Coast Guard,Verified,39.427700,26.388500
32,37,Drowning,NaN,NaN,1.0,1.0,Mediterranean,27/10/2015,Haberleber,Partially Verified,38.324300,26.288780
34,39,Suffocation,NaN,NaN,NaN,52.0,Mediterranean,26/08/2015,IOM Rome,Partially Verified,34.343400,15.117200
35,42,NaN,NaN,Nigerian,NaN,1.0,Mediterranean,23/08/2015,IOM Tunisia,Verified,34.865700,12.604900
37,45,Drowning,NaN,NaN,NaN,43.0,Mediterranean,25/10/2015,Disaster Alert Network,Verified,32.505100,14.510200
40,48,Drowning,NaN,NaN,NaN,6.0,Mediterranean,22/10/2015,Huffington Post,Partially Verified,32.750000,13.716700
50,64,Hit by train,NaN,NaN,NaN,1.0,Europe,15/10/2015,Reuters,Partially Verified,50.936400,1.799950
52,66,Drowning,NaN,Syria,NaN,3.0,Mediterranean,14/10/2015,Reuters,Partially Verified,39.277258,26.385503
53,67,Presumed drowning,NaN,NaN,NaN,1.0,Mediterranean,5/10/2015,IOM Greece,Verified,36.889300,27.182800
62,76,Vehicle accident,NaN,NaN,NaN,1.0,Europe,5/10/2015,Independent.mk,Unverified,42.309200,21.649900
63,77,Presumed drowning,NaN,NaN,NaN,2.0,Mediterranean,4/10/2015,"Reuters, SBS",Verified,36.891500,27.287700
64,78,Drowning,NaN,NaN,NaN,95.0,Mediterranean,1/10/2015,Times of Israel,Partially Verified,32.787300,12.782600
88,111,Presumed drowning,NaN,NaN,NaN,10.0,Mediterranean,2/5/2015,BBC/CBC,Partially Verified,35.460700,14.414100
93,120,Drowning,NaN,"Eritrea (2), Syria (1)",NaN,3.0,Mediterranean,20/04/2015,Reuters,Partially Verified,36.352782,27.938259
94,121,"Drowning, Asphyxiation",NaN,"Syria, Somalia, Gambia, Ivory Coast, Mali, Tun...",NaN,750.0,Mediterranean,18/04/2015,IOM Italy,Verified,35.030000,14.677700
98,125,Drowning,NaN,NaN,391.0,9.0,Mediterranean,13/04/2015,Guardian,Partially Verified,36.173400,17.572607

In [32]:
#Examinning subsets of data frame from the affected_nationality column to look for missing values only
data[data.affected_nationality.isnull()]

,id,cause_of_death,region_origin,affected_nationality,missing,dead,incident_region,date,source,reliability,lat,Ion
2,4,Presumed drowning,Middle East,NaN,NaN,1.0,Mediterranean,3/11/2015,Hellenic Coast Guard,Verified,36.504390,27.363253
3,6,Drowning,MENA,NaN,6.0,4.0,Mediterranean,1/11/2015,Reuters,Partially Verified,37.285600,27.086600
5,8,Drowning,MENA,NaN,NaN,11.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,37.751814,26.960291
6,9,Drowning,MENA,NaN,NaN,1.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,38.357540,26.452157
7,10,Drowning,MENA,NaN,NaN,1.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,39.276195,26.383443
8,11,Drowning,NaN,NaN,0.0,3.0,Mediterranean,28/10/2015,AP,Partially Verified,37.457800,26.972100
12,15,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,39.274069,26.386190
15,18,Drowning,NaN,NaN,NaN,1.0,Mediterranean,30/10/2015,AP,Partially Verified,39.274069,26.388250
17,20,Drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,30/10/2015,Hellenic Coast Guard,Verified,37.457800,26.972100
18,21,Drowning,NaN,NaN,32.0,7.0,Mediterranean,29/10/2015,Reuters España,Verified,35.244600,-3.931750
19,22,Drowning,Middle East/ South Asia,NaN,4.0,3.0,Mediterranean,29/10/2015,AP,Partially Verified,36.435000,28.217500
20,23,Drowning,Middle East/ South Asia,NaN,2.0,NaN,Mediterranean,29/10/2015,AP,Partially Verified,37.754800,26.977800
21,24,NaN,NaN,NaN,NaN,8.0,Mediterranean,20/10/2015,IOM Rome,Verified,40.334718,17.164603
22,25,Drowning,NaN,NaN,NaN,1.0,Mediterranean,2/10/2015,IOM Greece,Verified,36.952300,26.980800
23,28,Drowning,Middle East/ South Asia,NaN,NaN,4.0,Mediterranean,29/10/2015,Hurriyet Daily News,Partially Verified,39.470142,26.592653
24,29,Drowning,Middle East/ South Asia,NaN,NaN,2.0,Mediterranean,28/10/2015,AP,Verified,39.269816,26.390310
25,30,Drowning,Middle East/ South Asia,NaN,1.0,3.0,Mediterranean,28/10/2015,Associated Press and Hellenic Coast Guard,Verified,37.754800,26.977800
27,32,Presumed drowning,Middle East/ South Asia,NaN,NaN,19.0,Mediterranean,28/10/2015,AP,Partially Verified,36.952300,26.980800
28,33,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,1/10/2015,Hellenic Coast Guard,Verified,36.952300,26.980800
30,35,Died of unknown cause in hospital shortly afte...,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,28/10/2015,Hellenic Coast Guard,Verified,37.754800,26.977800
31,36,Drowning,NaN,NaN,13.0,43.0,Mediterranean,28/10/2015,IOM Greece and Hellenic Coast Guard,Verified,39.427700,26.388500
32,37,Drowning,NaN,NaN,1.0,1.0,Mediterranean,27/10/2015,Haberleber,Partially Verified,38.324300,26.288780
34,39,Suffocation,NaN,NaN,NaN,52.0,Mediterranean,26/08/2015,IOM Rome,Partially Verified,34.343400,15.117200
37,45,Drowning,NaN,NaN,NaN,43.0,Mediterranean,25/10/2015,Disaster Alert Network,Verified,32.505100,14.510200
38,46,Presumed drowning,Middle East/ South Asia,NaN,1.0,4.0,Mediterranean,21/10/2015,WWNT Radio,Partially Verified,39.274069,26.380010
39,47,Drowning,Middle East/ South Asia,NaN,1.0,2.0,Mediterranean,22/10/2015,Hurriyet Daily News,Partially Verified,39.319200,26.601763
40,48,Drowning,NaN,NaN,NaN,6.0,Mediterranean,22/10/2015,Huffington Post,Partially Verified,32.750000,13.716700
41,49,Drowning,MENA,NaN,11.0,12.0,Mediterranean,22/10/2015,Hurriyet Daily News,Verified,39.410744,26.586906
43,53,NaN,South East Asia,NaN,NaN,24.0,Southeast Asia,23/08/2015,"BBC, UNHCR",Verified,6.444910,100.205000
45,57,NaN,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,18/10/2015,Hellenic Coast Guard via IOM Greece,Verified,37.295400,27.112700
48,62,Presumed drowning,Middle East/ South Asia,NaN,1.0,7.0,Mediterranean,15/10/2015,IOM Greece,Verified,39.288950,26.388250
50,64,Hit by train,NaN,NaN,NaN,1.0,Europe,15/10/2015,Reuters,Partially Verified,50.936400,1.799950
53,67,Presumed drowning,NaN,NaN,NaN,1.0,Mediterranean,5/10/2015,IOM Greece,Verified,36.889300,27.182800
54,68,Shot,Central America & Mexico,NaN,NaN,1.0,Central America incl. Mexico,5/10/2015,Agenda Tlaxcala,Partially Verified,19.408000,-98.052000
62,76,Vehicle accident,NaN,NaN,NaN,1.0,Europe,5/10/2015,Independent.mk,Unverified,42.309200,21.649900
63,77,Presumed drowning,NaN,NaN,NaN,2.0,Mediterranean,4/10/2015,"Reuters, SBS",Verified,36.891500,27.287700
64,78,Drowning,NaN,NaN,NaN,95.0,Mediterranean,1/10/2015,Times of Israel,Partially Verified,32.787300,12.782600
72,91,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,24/09/2015,Hellenic Coast Guard via IOM Greece,Verified,37.466700,26.966700
74,94,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,23/09/2015,IOM Greece,Verified,39.367100,26.175100
75,95,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,22/09/2015,IOM Greece/AFP,Partially Verified,39.382400,26.486400
77,98,Drowning,Middle East/ South Asia,NaN,2.0,NaN,Mediterranean,20/09/2015,Coast Guard Command,Verified,39.235700,26.665000
78,100,Drowning. Boat collided with ferry,Middle East/ South Asia,NaN,13.0,13.0,Mediterranean,20/09/2015,IOM/Coast Guard Command/Indian Express,Partially Verified,39.445562,26.042874
79,101,Fell from train,Central America & Mexico,NaN,NaN,1.0,Central America incl. Mexico,20/09/2015,Red-accion,Partially Verified,19.709800,-98.971500
88,111,Presumed drowning,NaN,NaN,NaN,10.0,Mediterranean,2/5/2015,BBC/CBC,Partially Verified,35.460700,14.414100
92,119,Drowning,Central America & Mexico,NaN,NaN,1.0,U.S./Mexico Border,21/04/2015,Televisa,Partially Verified,27.495413,-99.522649
98,125,Drowning,NaN,NaN,391.0,9.0,Mediterranean,13/04/2015,Guardian,Partially Verified,36.173400,17.572607

In [33]:
#Examinning subsets of data frame from the missing column to look for missing values only
data[data.missing.isnull()]

,id,cause_of_death,region_origin,affected_nationality,missing,dead,incident_region,date,source,reliability,lat,Ion
1,3,Fell from train,Central America & Mexico,Honduras,NaN,1.0,Central America incl. Mexico,3/11/2015,La Jornada,Partially Verified,15.956400,-93.663100
2,4,Presumed drowning,Middle East,NaN,NaN,1.0,Mediterranean,3/11/2015,Hellenic Coast Guard,Verified,36.504390,27.363253
4,7,Vehicle accident,South East Asia,Cambodia,NaN,4.0,Southeast Asia,1/11/2015,Phnom Penh Post,Partially Verified,13.361100,100.985000
5,8,Drowning,MENA,NaN,NaN,11.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,37.751814,26.960291
6,9,Drowning,MENA,NaN,NaN,1.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,38.357540,26.452157
7,10,Drowning,MENA,NaN,NaN,1.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,39.276195,26.383443
9,12,Died of unknown cause in hospital shortly afte...,MENA,Syria,NaN,1.0,Mediterranean,28/10/2015,IOM Greece,Verified,39.370816,26.176473
10,13,Drowning,MENA,Iran,NaN,1.0,Mediterranean,26/10/2015,IOM Greece,Verified,39.280978,26.384130
12,15,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,1/11/2015,Hellenic Coast Guard,Verified,39.274069,26.386190
13,16,Drowning,NaN,Afghanistan,NaN,4.0,Mediterranean,31/10/2015,Hurriyet Daily News,Partially Verified,39.279915,26.388937
14,17,Exposure. Died upon entry to refugee camp.,South Asia,Afghan,NaN,1.0,Europe,31/10/2015,AP,Partially Verified,45.260400,19.170600
15,18,Drowning,NaN,NaN,NaN,1.0,Mediterranean,30/10/2015,AP,Partially Verified,39.274069,26.388250
16,19,Drowning,Sub-Saharan Africa,Likely Comorian,NaN,8.0,Sub-Saharan Africa,30/10/2015,LINFO,Partially Verified,-11.802800,43.851900
17,20,Drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,30/10/2015,Hellenic Coast Guard,Verified,37.457800,26.972100
21,24,NaN,NaN,NaN,NaN,8.0,Mediterranean,20/10/2015,IOM Rome,Verified,40.334718,17.164603
22,25,Drowning,NaN,NaN,NaN,1.0,Mediterranean,2/10/2015,IOM Greece,Verified,36.952300,26.980800
23,28,Drowning,Middle East/ South Asia,NaN,NaN,4.0,Mediterranean,29/10/2015,Hurriyet Daily News,Partially Verified,39.470142,26.592653
24,29,Drowning,Middle East/ South Asia,NaN,NaN,2.0,Mediterranean,28/10/2015,AP,Verified,39.269816,26.390310
26,31,Drowning,NaN,Afghanistan,NaN,3.0,Mediterranean,28/10/2015,Reuters and Al Jazeera,Partially Verified,39.274600,26.392370
27,32,Presumed drowning,Middle East/ South Asia,NaN,NaN,19.0,Mediterranean,28/10/2015,AP,Partially Verified,36.952300,26.980800
28,33,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,1/10/2015,Hellenic Coast Guard,Verified,36.952300,26.980800
29,34,Drowning,NaN,Afghanistan,NaN,1.0,Mediterranean,28/10/2015,Hellenic Coast Guard,Verified,39.277258,26.409536
30,35,Died of unknown cause in hospital shortly afte...,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,28/10/2015,Hellenic Coast Guard,Verified,37.754800,26.977800
33,38,Drowning,MENA,Syrian,NaN,1.0,Mediterranean,26/10/2015,IOM Greece and AP,Verified,38.373153,26.460397
34,39,Suffocation,NaN,NaN,NaN,52.0,Mediterranean,26/08/2015,IOM Rome,Partially Verified,34.343400,15.117200
35,42,NaN,NaN,Nigerian,NaN,1.0,Mediterranean,23/08/2015,IOM Tunisia,Verified,34.865700,12.604900
36,43,Drowning,Sub-Saharan Africa,Guinean,NaN,1.0,Mediterranean,26/10/2015,AFP,Partially Verified,35.883837,-5.317573
37,45,Drowning,NaN,NaN,NaN,43.0,Mediterranean,25/10/2015,Disaster Alert Network,Verified,32.505100,14.510200
40,48,Drowning,NaN,NaN,NaN,6.0,Mediterranean,22/10/2015,Huffington Post,Partially Verified,32.750000,13.716700
43,53,NaN,South East Asia,NaN,NaN,24.0,Southeast Asia,23/08/2015,"BBC, UNHCR",Verified,6.444910,100.205000
...,...,...,...,...,...,...,...,...,...,...,...,...
63,77,Presumed drowning,NaN,NaN,NaN,2.0,Mediterranean,4/10/2015,"Reuters, SBS",Verified,36.891500,27.287700
64,78,Drowning,NaN,NaN,NaN,95.0,Mediterranean,1/10/2015,Times of Israel,Partially Verified,32.787300,12.782600
65,79,Hit by train,Horn of Africa,Eritrea,NaN,1.0,Europe,30/09/2015,CNN,Partially Verified,50.917100,1.792770
66,82,drowning,South Asia,Afghan,NaN,2.0,Mediterranean,30/09/2015,IOM Greece,Verified,39.334600,26.475500
67,83,NaN,South America,Ecuadorian,NaN,3.0,Central America incl. Mexico,30/09/2015,El Universo,Partially Verified,19.173800,-96.134200
68,85,Hi by truck,Middle East/ South Asia,Iraqi,NaN,1.0,Europe,29/09/2015,BBC,Partially Verified,50.951300,1.858690
70,87,Crushed to death,Middle East/ South Asia,Iraqi,NaN,1.0,Europe,29/09/2015,BBC,Partially Verified,50.951300,1.858690
71,89,Drowning,MENA,"Mostly from Syria, possibly some from Iraq",NaN,17.0,Mediterranean,27/09/2015,Hurriyet Daily News,Partially Verified,37.013567,27.181960
72,91,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,24/09/2015,Hellenic Coast Guard via IOM Greece,Verified,37.466700,26.966700
73,92,Hit by train,Horn of Africa,Likely Eritrea,NaN,1.0,Europe,24/09/2015,BBC,Partially Verified,50.923200,1.782850
74,94,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,23/09/2015,IOM Greece,Verified,39.367100,26.175100
75,95,Presumed drowning,Middle East/ South Asia,NaN,NaN,1.0,Mediterranean,22/09/2015,IOM Greece/AFP,Partially Verified,39.382400,26.486400
79,101,Fell from train,Central America & Mexico,NaN,NaN,1.0,Central America incl. Mexico,20/09/2015,Red-accion,Partially Verified,19.709800,-98.971500
80,102,Drowning,Middle East,Syria,NaN,13.0,Mediterranean,19/09/2015,IOM Greece,Verified,39.387700,26.431500
81,103,Drowning,MENA,Syrian,NaN,1.0,Mediterranean,18/09/2015,Anadolu Agency,Partially Verified,38.328609,26.293587
82,104,Electrocution,Middle East/ South Asia,Syria,NaN,1.0,Europe,18/09/2015,BBC,Partially Verified,50.951500,1.845700
83,105,NaN,Sub-Saharan Africa,Nigerian,NaN,1.0,Mediterranean,17/09/2015,Migrant Offshore Aid Station (MOAS),Verified,33.724300,14.436000
84,106,Drowning,Middle East,"Reported as unspecified nationals of Syria, Af...",NaN,22.0,Mediterranean,15/09/2015,RTE News and Turkish Coast Guard,Verified,36.719100,27.338800
85,107,Drowning,MENA,Syrian,NaN,2.0,Mediterranean,14/09/2015,Hurriyet Daily News,Partially Verified,38.007019,27.101857
86,108,Drowning,MENA,Syria,NaN,1.0,Mediterranean,5/9/2015,IOM Greece,Verified,37.500500,27.079100
87,109,Hit by vehicle,Horn of Africa,Eritrea,NaN,1.0,Europe,24/07/2015,The Express,Partially Verified,50.148700,1.889650
88,111,Presumed drowning,NaN,NaN,NaN,10.0,Mediterranean,2/5/2015,BBC/CBC,Partially Verified,35.460700,14.414100
89,112,NaN,South East Asia,Rohingya,NaN,36.0,Southeast Asia,1/5/2015,Arakan Project,Verified,7.189770,100.595000
90,113,"Unknown, torture involved",South East Asia,Myanmar,NaN,106.0,Southeast Asia,25/05/2015,BBC,Partially Verified,6.444910,100.578535
91,114,Train accident,MENA,Afghanistan,NaN,1.0,Europe,24/04/2015,Radio Free Europe,Partially Verified,41.557900,21.818800
92,119,Drowning,Central America & Mexico,NaN,NaN,1.0,U.S./Mexico Border,21/04/2015,Televisa,Partially Verified,27.495413,-99.522649
93,120,Drowning,NaN,"Eritrea (2), Syria (1)",NaN,3.0,Mediterranean,20/04/2015,Reuters,Partially Verified,36.352782,27.938259
94,121,"Drowning, Asphyxiation",NaN,"Syria, Somalia, Gambia, Ivory Coast, Mali, Tun...",NaN,750.0,Mediterranean,18/04/2015,IOM Italy,Verified,35.030000,14.677700
95,122,Burns from cooking gas explosion in connection...,Sub-Saharan Africa,Eritrea or Somalia,NaN,1.0,Mediterranean,17/04/2015,UNHCR,Verified,35.173800,17.226600
96,123,Drowning,Sub-Saharan Africa,"Survivors from Nigeria, Ghana, Niger",NaN,41.0,Mediterranean,16/04/2015,BBC and CBC,Partially Verified,35.746500,14.414100

In [34]:
#Examinning subsets of data frame from the dead column to look for missing values only
data[data.dead.isnull()]

,id,cause_of_death,region_origin,affected_nationality,missing,dead,incident_region,date,source,reliability,lat,Ion
20,23,Drowning,Middle East/ South Asia,NaN,2.0,NaN,Mediterranean,29/10/2015,AP,Partially Verified,37.7548,26.9778
77,98,Drowning,Middle East/ South Asia,NaN,2.0,NaN,Mediterranean,20/09/2015,Coast Guard Command,Verified,39.2357,26.6650
97,124,Drowning after being thrown overboard by other...,Sub-Saharan Africa,"Ghana, Nigeria",12.0,NaN,Mediterranean,16/04/2015,BBC and CBC,Partially Verified,34.8859,14.4141

In [35]:
#Total rows and columns in the dataset
data.shape

(99, 12)

In [39]:
#Absolutely drop records which no describe cause of death (classmate instruction)
data.dropna(subset=['cause_of_death'], how='all').shape

(92, 12)

### Conclusion:  
*7 rows containing missing values in the colum,  cause_of_death*